version: '3.8'

services:
  viet-test-next:
    build: .
    container_name: viet-test-next
    ports:
      - "7000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - my-network
    command: yarn start

networks:
  my-network:
    external: true
